import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillGithub, AiFillBook } from "react-icons/ai";
import Image from "next/image";
import Jonghan from "../public/dev-ed-wave.png"; //TODO : 안경쓴 개발자 이미지
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>김종한의 포트폴리오</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40">
        <section className="">
          <nav className="mb-12 flex justify-between py-10">
            <h1 className="font-burtons text-xl">JONGHAN</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className="ml-8 rounded-md bg-gradient-to-r from-cyan-500 to-teal-500 px-4 py-2 text-white"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="p-10 py-10 text-center">
            <h2 className="text py-2 text-5xl font-medium text-teal-600 md:text-6xl">
              김종한
            </h2>
            <h3 className="py-2 text-2xl md:text-3xl">Frontend Developer</h3>
            <p className="text-md mx-auto max-w-lg py-5 leading-8 text-gray-800 md:text-xl">
              세상을 깜짝 놀라게 만들 앱을 만들고 싶어요
            </p>
          </div>
          <div className="flex justify-center gap-16 py-3 text-5xl text-gray-600">
            <AiFillGithub />
            <AiFillBook />
          </div>
          <div className="relative mx-auto mt-20 h-80 w-80 overflow-hidden rounded-full bg-gradient-to-b from-teal-500 md:h-96 md:w-96">
            <Image
              src={Jonghan}
              alt="Greeting Image"
              layout="fill"
              objectFit="cover" // TODO: deprecated 고치기
            />
          </div>
        </section>
        {/*section2*/}
        <section>
          <div>
            <h3 className="py-1 text-3xl">Services I offer</h3>
            <p className="text-md text py-2 leading-8 text-gray-800">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit.
              Accusantium aliquid animi, aspernatur consequuntur corporis culpa
              <span className="text-teal-500">agencies</span>delectus eos fuga
              ipsam laboriosam laborum neque nisi obcaecati odit quidem quo
              reprehenderit totam vero!
              <span className="text-teal-500">startups</span>
            </p>
            <p className="text-md text py-2 leading-8 text-gray-800">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit.
              Accusantium aliquid animi, aspernatur consequuntur corporis culpa
              <span className="text-teal-500">agencies</span>delectus eos fuga
              ipsam laboriosam laborum neque nisi obcaecati odit quidem quo
              reprehenderit totam vero!
              <span className="text-teal-500">startups</span>
            </p>
          </div>
          <div className="my-10 rounded-xl p-10 text-center shadow-lg">
            <Image src={consulting} width={100} height={100} alt="box" />
            <h3 className="pt-8 pb-2 text-lg font-medium">Beautiful Designs</h3>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit.
              Aspernatur explicabo nostrum porro qui, quia sequi voluptate.
              Dolore eius molestiae nam odio quis. Asperiores blanditiis esse
              hic omnis optio tempore ullam?
            </p>
            <h4 className="py-4 text-teal-600">Design tools I use</h4>
            <p className="py-1 text-gray-800">Photoshop</p>
            <p className="py-1 text-gray-800">Illustraor</p>
            <p className="py-1 text-gray-800">Figma</p>
          </div>
          <div className="my-10 rounded-xl p-10 shadow-lg">
            <Image src={design} width={100} height={100} alt="box" />
            <h3 className="pt-8 pb-2 text-lg font-medium">Beautiful Designs</h3>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit.
              Aspernatur explicabo nostrum porro qui, quia sequi voluptate.
              Dolore eius molestiae nam odio quis. Asperiores blanditiis esse
              hic omnis optio tempore ullam?
            </p>
            <h4 className="py-4 text-teal-600">Design tools I use</h4>
            <p className="py-1 text-gray-800">Photoshop</p>
            <p className="py-1 text-gray-800">Illustraor</p>
            <p className="py-1 text-gray-800">Figma</p>
          </div>
          <div className="my-10 rounded-xl p-10 text-center shadow-lg">
            <Image src={code} width={100} height={100} alt="box" />
            <h3 className="pt-8 pb-2 text-lg font-medium">Beautiful Designs</h3>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit.
              Aspernatur explicabo nostrum porro qui, quia sequi voluptate.
              Dolore eius molestiae nam odio quis. Asperiores blanditiis esse
              hic omnis optio tempore ullam?
            </p>
            <h4 className="py-4 text-teal-600">Design tools I use</h4>
            <p className="py-1 text-gray-800">Photoshop</p>
            <p className="py-1 text-gray-800">Illustraor</p>
            <p className="py-1 text-gray-800">Figma</p>
          </div>
        </section>
        <section>
          <div>
            <h3 className="py-1 text-3xl">Portfolio</h3>
          </div>
          <div>
            <div>
              <Image src={web1} alt="portfolio image" />
            </div>
            <div>
              <Image src={web2} alt="portfolio image" />
            </div>
            <div>
              <Image src={web3} alt="portfolio image" />
            </div>
            <div>
              <Image src={web4} alt="portfolio image" />
            </div>
            <div>
              <Image src={web5} alt="portfolio image" />
            </div>
            <div>
              <Image src={web6} alt="portfolio image" />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
